version: '3'

services:
  web:
    image: nginx:1.17.8-alpine
    ports:
      - "8811:80"
    volumes:
      - .:/app/
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    links:
      - php

  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    expose:
      - "9888:9000"
    volumes:
      - ./public:/app
      - ./docker/php/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini